CREATE TABLE hero
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                             NOT NULL,
    role_id INTEGER,
    CONSTRAINT pk_hero PRIMARY KEY (id)
);

ALTER TABLE hero
    ADD CONSTRAINT FK_HERO_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);