CREATE TABLE weapon
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    aimtype_id INTEGER,
    hero_id    INTEGER                                  NOT NULL,
    CONSTRAINT pk_weapon PRIMARY KEY (id)
);

ALTER TABLE weapon
    ADD CONSTRAINT FK_WEAPON_ON_AIMTYPE FOREIGN KEY (aimtype_id) REFERENCES aimtype (id);

ALTER TABLE weapon
    ADD CONSTRAINT FK_WEAPON_ON_HERO FOREIGN KEY (hero_id) REFERENCES hero (id);