CREATE TABLE admin_role
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_admin_role PRIMARY KEY (id)
);

INSERT INTO admin_role (name)
VALUES ('GRANT_ADMIN');

CREATE TABLE admin_user
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255)                             NOT NULL,
    password      VARCHAR(255)                             NOT NULL,
    active        BOOLEAN                                  NOT NULL,
    admin_role_id INTEGER,
    CONSTRAINT pk_admin_user PRIMARY KEY (id)
);

ALTER TABLE admin_user
    ADD CONSTRAINT idx_user_email UNIQUE (email);

ALTER TABLE admin_user
    ADD CONSTRAINT FK_ADMIN_USER_ON_ADMIN_ROLE FOREIGN KEY (admin_role_id) REFERENCES admin_role (id);

INSERT INTO admin_user (active, email, password, admin_role_id)
VALUES ('true', 'test@test.com', '$2a$10$SM1ERfi69u5uzJURXZ9csulgIFWMlUYR2Ru1RAggnzewGnoC0.zUu',
        (SELECT ar.id FROM admin_role ar WHERE ar.name = 'GRANT_ADMIN'));